### ISSUE TITLE
Zotero code to facilitate download of document library

### ISSUE THREAD

**Issue by kikenni** [retorquere/zotero-debug-log#1]
I have a group library in Zotero containing about 3 GB of Word and PDF documents. I would like to export these documents to my computer and maintain the same folder structure that I have within Zotero.

I found this downloadable code on GitHub: https://gist.github.com/retorquere/6bad138046bc0c7b0420166ebcb90028 

I can now ctrl-click on the group library and 'Export Library...' then 'file heriarchy' and it starts to export the file structure and files to my computer. But after about 70 files it says "an error occurred while trying to export the selected file" and the process halts. I use a Mac so a colleague tried with a PC, but got the same error. Seems like there may be something about a particular file in my Zotero library that the exporter does not like.

Has anyone experienced a similar problem and found a solution?

**Comment by retorquere** [comment]
Can you install https://github.com/retorquere/zotero-debug-log/releases/tag/v2.0.10, try the export again, then go into the help menu, select `Send debug log to file.io` from the `Help` menu, then post the ID you get here.

**Comment by kikenni** [comment]
How do I install that? I see a file ending .xpi, a zip file and a tar.gz file. Sorry I am technically illiterate!

**Comment by retorquere** [comment]
No problem. Right-click the xpi and save, in Zotero go to tools, adsons, gear menu, install from file, and select the xpi you just downloaded.

**Comment by kikenni** [comment]
Thanks. Debug log ID is FPW2aw1HjBHr-YBEXKN44

**Comment by retorquere** [comment]
Apologies -- I had forgotten that I had put up a fixed version at https://github.com/retorquere/zotero-file-hierarchy. You can uninstall the debug plugin.

**Comment by kikenni** [comment]
Thanks, works perfectly!
